//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBDBapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.tblCasts = new HashSet<Cast>();
        }
    
        public int FilmID { get; set; }
        public string FilmName { get; set; }
        public System.DateTime FilmReleaseDate { get; set; }
        public int FilmDirectorID { get; set; }
        public int FilmLanguageID { get; set; }
        public int FilmCountryID { get; set; }
        public Nullable<int> FilmStudioID { get; set; }
        public string FilmSynopsis { get; set; }
        public int FilmRunTimeMinutes { get; set; }
        public Nullable<long> FilmCertificateID { get; set; }
        public Nullable<int> FilmBudgetDollars { get; set; }
        public Nullable<int> FilmBoxOfficeDollars { get; set; }
        public int FilmOscarNominations { get; set; }
        public int FilmOscarWins { get; set; }
    
        public virtual tblCertificate tblCertificate { get; set; }
        public virtual Country tblCountry { get; set; }
        public virtual Director tblDirector { get; set; }
        public virtual tblLanguage tblLanguage { get; set; }
        public virtual Studio tblStudio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cast> tblCasts { get; set; }
    }
}
